{% set name = "pyspelling" %}
{% set version = "2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspelling-{{ version }}.tar.gz
  sha256: df74c42e6e24171b7e1a83ac62fa2e151028ac045817c4f0384791c2d6099c5c
  patches:
    - no_versioned_entrypoint.patch

build:
  number: 0
  noarch: python
  entry_points:
    - pyspelling=pyspelling.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling >=0.21.1
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - soupsieve >=1.8
    - markdown
    - pyyaml
    - wcmatch >=8.5
    - lxml
    - html5lib

test:
  imports:
    - pyspelling
    - pyspelling.filters
  commands:
    - pip check
    - pyspelling --help
  requires:
    - pip

about:
  home: https://github.com/facelessuser/pyspelling
  summary: Spell checker
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
