{% set name = "pyspelling" %}
{% set version = "2.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspelling-{{ version }}.tar.gz
  sha256: 823afba99a77de58c1fc53b3cac712bb2335dacee410a1a14d150e94d3439f3e
  patches:
    - no_versioned_entrypoint.patch

build:
  number: 0
  noarch: python
  entry_points:
    - pyspelling=pyspelling.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling >=0.21.1
  run:
    - python >=3.6
    - beautifulsoup4
    - html5lib
    - lxml
    - markdown
    - pyyaml
    - soupsieve >=1.8
    - wcmatch >=6.0.3

test:
  imports:
    - pyspelling
    - pyspelling.filters
  commands:
    - pip check
    - pyspelling --help
  requires:
    - pip

about:
  home: https://github.com/facelessuser/pyspelling
  summary: Spell checker
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
