{% set name = "pyspelling" %}
{% set version = "2.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspelling-{{ version }}.tar.gz
  sha256: 7b397911e46b7fa7c1056b2867c02e81547fc8d00bbcd84465655df23e49dbaa
  patches:
    - no_versioned_entrypoint.patch

build:
  number: 0
  noarch: python
  entry_points:
    - pyspelling=pyspelling.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - soupsieve >=1.8
    - markdown
    - pyyaml
    - wcmatch >=8.5
    - lxml
    - html5lib

test:
  imports:
    - pyspelling
    - pyspelling.filters
  commands:
    - pip check
    - pyspelling --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facelessuser/pyspelling
  summary: Spell checker
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
